#!/bin/bash

echo '###################### building image ######################'
docker build -t st1991/sampling-service:latest .
echo '###################### loading containers ######################'
docker-compose up -d
sleep 5
echo '###################### testing ######################'
python3 test.py
echo '###################### cleaning ######################'
docker-compose down